image: alpine:latest

stages:
  - test
  - build
  - review
  - stage
  - prod

test_crawler-engine:
  stage: test
  image: python:3.7.4
  tags:
    - infra
  script:
    - cd crawler-engine &&
      pip install -r requirements.txt -r requirements-test.txt
    - python -m unittest discover -s tests/
    - coverage run -m unittest discover -s tests/
    - coverage report --include crawler/crawler.py
  coverage: '/\d+%/'

test_crawler-ui:
  stage: test
  image: python:3.7.4
  tags:
    - infra
  script:
    - cd crawler-ui &&
      pip install -r requirements.txt -r requirements-test.txt
    - python -m unittest discover -s tests/
    - coverage run -m unittest discover -s tests/
    - coverage report --include ui/ui.py
  coverage: '/\d+%/'

build_crawler-engine:
  stage: build
  image: docker:19.03
  # services:
  #   - name: docker:19.03-dind
  tags:
    - infra
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - cd crawler-engine
  script:
    - docker build -t
      $CI_REGISTRY_USER/crawler-engine:$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID .
    - if [[ -n $CI_COMMIT_TAG ]];
      then docker tag
      $CI_REGISTRY_USER/crawler-engine:$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID
      $CI_REGISTRY_USER/crawler-engine:$CI_COMMIT_TAG; fi
    - docker push

build_crawler-ui:
  stage: build
  image: docker:19.03
  # services:
  #   - name: docker:19.03-dind
  tags:
    - infra
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - cd crawler-ui
  script:
    - docker build -t
      $CI_REGISTRY_USER/crawler-ui:$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID .
    - if [[ -n $CI_COMMIT_TAG ]];
      then docker tag
      $CI_REGISTRY_USER/crawler-ui:$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID
      $CI_REGISTRY_USER/crawler-ui:$CI_COMMIT_TAG; fi
    - docker push

review:
  stage: review
  tags:
    - infra
  script:
    - echo 'Review stage'

stagging:
  stage: stage
  when: manual
  only:
    - dev
    - master
  tags:
    - stage
  script:
    - echo 'Deploy to stage'
  environment:
    name: stage
    url: https://stage.crawler.com

production:
  stage: prod
  when: manual
  only:
    - tags
  tags:
    - prod
  script:
    - echo 'Deploy to prod'
  environment:
    name: prod
    url: https://crawler.com
